set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -s escape-time 0
set -g history-limit 50000
set -g display-time 2000
set -g status-interval 3
set -g focus-events on

set -g mouse on
unbind %
unbind '"'
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind r source-file ~/.tmux.conf \; display "Tmux Configuration Reloaded!"


set -g status-position bottom
set -g status-justify left
set -g status-style "bg=default,fg=default"
set -g status-left-length 20
set -g status-left "#[bg=color2,fg=color0,bold]    #S #[bg=default,fg=default] "
set -g status-right-length 50
set -g status-right "#[fg=color8]   #{scroll_position} #[fg=color3]    %H:%M "
setw -g window-status-current-style "bg=color8,fg=color3,bold"
setw -g window-status-current-format " #I:#W* "
setw -g window-status-format " #I:#W  "
set -g pane-border-style "fg=color8"
set -g pane-active-border-style "fg=color3"
set -g mode-style "bg=color8,fg=color3,bold"

set -s set-clipboard on
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @yank_selection 'clipboard'
set -g @yank_selection_mouse 'clipboard'
set -g @yank_action 'copy-pipe'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe

run '~/.tmux/plugins/tpm/tpm'
